### ISSUE TITLE
Format on save undoes all changes in file

### ISSUE THREAD

**Issue by tterranigma** [z0mbix/vim-shfmt#2]
I think the logic of the plugin it to before saving to format the file. But the file that is being formatted is the one without the changes and this is what is being saved.

Probably related to the above is the fact that the undo history gets deleted for the file in question after saving, even if `set hidden` is present.

**Comment by tterranigma** [comment]
This might be relevant to the undo history issue
https://stackoverflow.com/questions/24690441/call-a-function-without-adding-to-undo-list

I am at my limits of vimscript here to move further.

**Comment by z0mbix** [comment]
@tterranigma Thanks for the report, and sorry about the delay in getting to this. I have just updated master (#3) with your change, and it is still working for me. I don't really know how to handle the undo history problem right now, but I have been looking at other similar plugins which also don't handle this well, so not sure how best to solve that one.

CC: @sublimino @radioinmyhead
