### ISSUE TITLE
Autosave Output Slow and Huge

### ISSUE THREAD

**Issue by stefanthorpe** [z0mbix/vim-shfmt#4]
Firstly love this plugin Thanks!

I have `let g:shfmt_fmt_on_save = 1` enabled and it works great. The only issue is that now I've enabled it when I save I get screens and screens of the code image below. The length of this varies from files to file and when it's one or 2 lines its ok. But when its pages, I save then have to sit and repeatedly hit more.

Any Idea how I can suppress this output?

![screenshot-2018-11-1831](https://user-images.githubusercontent.com/6477766/48809500-ddaad000-ecf2-11e8-85fc-2af7dde2bce9.png)

**Comment by z0mbix** [comment]
I haven’t seen this behaviour before, but will take a look to see why this may be happening.

**Comment by z0mbix** [comment]
I have been using this plugin for years and never seen this issue, so I'm presuming it's some kind of specific vim config/plugin problem, so I'm closing this.
